### ISSUE TITLE
你好，可否添加列表里没有的词典？

### ISSUE THREAD

**Issue by minshifu** [pnlpal/dictionaries#15]
非常好的扩展，界面也很漂亮。请问能否实现用户自我添加词典的功能？比如我想添加linguee.com等目前列表里没有的词典或翻译界面。非常感谢！

**Comment by revir** [comment]
Yes, 下一个版本就可以， 正在发布中。

**Comment by minshifu** [comment]
好的，多谢哈 ~！

**Comment by revir** [comment]
新版本有了一个思路， 可以通过github上的远程配置来添加词典， 也可以在本地通过代码来添加词典。
见： https://github.com/revir/dictionaries/blob/master/more-dicts.md

欢迎给我 pull request

**Comment by minshifu** [comment]
感谢，我看下

**Comment by rubcap** [comment]
I concur. Very nice interface, but I miss the option to add dictionaries myself. 
Also: which dictionary is used in the floating definition pop-up? That's not entirely clear to me.

Great work!

**Comment by revir** [comment]
@rubcap  Thank you. The floating definition of English & Chinese is from Bing Dict.
To add extra dictionary please send me a pull request, or just tell me in the issue. It could benefit everyone else, right?

**Comment by revir** [comment]
Now I have another pretty good solution, add extra dictionaries from: https://pnlpal.dev/category/4/dictionariez-trove
