### ISSUE TITLE
Disable loading dialog?

### ISSUE THREAD

**Issue by tmpm697** [pnlpal/dictionaries#31]
Personally I find loading dialog a bit of distraction, the definition page should appear once it has data to display, how to disable loading dialog box (the one with three dots)?

**Comment by revir** [comment]
Interesting, I disabled it once for a time, but then I found it's intimidating not knowing it's working or not. So I reopened it.

Since you prefer the other way, I will add an option to it.

**Comment by tmpm697** [comment]
Thanks, I find it a bit weird for a "waiting dialog", but you can change cursor to loading state (circle form) instead of a dialog, is that possible for an app to change cursor shape?

**Comment by revir** [comment]
Interesting idea, I will take a try.

--------------
*River*


tmpm697 <notifications@github.com> 于2020年11月24日周二 下午2:37写道：
