### ISSUE TITLE
Always loading

### ISSUE THREAD

**Issue by e1399579** [pnlpal/dictionaries#32]
I selected one english word,but always loading.I'm chinese,when i use vpn,it worked.
一直加载，应该是服务器不能访问，可以换服务器吗？

**Comment by revir** [comment]
抱歉，因为使用了Google的搜索结果。我考虑下怎么办。

--------------
*River*


e1399579 <notifications@github.com> 于2020年11月25日周三 下午4:26写道：

**Comment by revir** [comment]
目前初步解决方案是Google结果获取不到就回退到 Bing. 虽然时间会长一丢丢， 但至少不是 always loading 了。

**Comment by e1399579** [comment]
我认为加一个选项到设置里面会更好🤣

**Comment by revir** [comment]
OK, I will do it.

**Comment by revir** [comment]
该选项在最新版本里已加上。
![image](https://user-images.githubusercontent.com/3252034/104117338-81381e00-535b-11eb-9bcf-43b686daf861.png)
