### ISSUE TITLE
option to reset settings

### ISSUE THREAD

**Issue by mkeroppi** [pnlpal/dictionaries#36]
I'm unable to reset settings or add default dictionaries that were removed.

**Comment by revir** [comment]
Sorry, what are the  dictionaries that you deleted?  I am going to add those to [Dictionariez trove](https://pnlpal.dev/category/4/dictionariez-trove), so that you could get them back. 

Reset settings? Good idea.

**Comment by mkeroppi** [comment]
wiktionary

**Comment by revir** [comment]
https://pnlpal.dev/topic/50/wiktionary

**Comment by revir** [comment]
I leave the issue here for reminding me a lot of the default dictionaries are waiting to add into the trove.

**Comment by revir** [comment]
Now v2.6.1 has a "restore default dictionaries" btn.
