### ISSUE TITLE
划词翻译时不一定能显示中文释义

### ISSUE THREAD

**Issue by frostRed** [pnlpal/dictionaries#37]
但是右键里面手动点『Look up』这个去查的话又是能查到中文释义的。

**Comment by revir** [comment]
意思是有时有中文，有时没有？
设置里选择了“Show Chinese definition for some languages” 也一样吗？

**Comment by frostRed** [comment]
对，我已经勾选了。但不是同一个单词会时有时无。而是对于有些可能偏僻的单词不会显示中文，但右键去查又是有中文释义的。等下次我碰到，我提供一下单词样本吧。

**Comment by frostRed** [comment]
`surveillance` 划词翻译，第一次只有英文，没有中文，右键查到有显示中文，然后我再划词翻译，就同时有中文和英文了。
`observation` 划词一直不会显示中文。

**Comment by revir** [comment]
V2.7.4 终于应该解决了这个问题， 请试试？ 不过chrome版本还在审核中，过几天即可测试。
