### ISSUE TITLE
Twitter 网页深色模式下划词翻译会显示混乱

### ISSUE THREAD

**Issue by frostRed** [pnlpal/dictionaries#38]
![image](https://user-images.githubusercontent.com/2486301/103065481-9f7aeb80-45f1-11eb-8d30-ac5bdb1b44cb.png)
如图，网页的右侧会变成一片空白。

**Comment by revir** [comment]
发现了。
临时解决方法： 暂时禁用设置里的“ Highlight your selected words in yellow ”

**Comment by revir** [comment]
Now you can safely turn on the setting of “ Highlight your selected words in yellow ”. 
Twitter is just excluded.
