### ISSUE TITLE
Sorting by rate column works incorrectly in lookup history

### ISSUE THREAD

**Issue by s23706** [pnlpal/dictionaries#41]
**Pre-requisites:**
- There are several words in lookup history

**Steps to reproduce:**
1. Open lookup history
2. Rate a word (do not refresh the page after it)
3. Sort the table by the rate column

**Expected result**
Words are sorted correctly based on the selected sorting configuration.

**Actual result**
Words are sorted incorrectly. See the attachment demonstrating the behavior. In this case, the word "programming" had been rated.

**Environments:** Chrome 87.0.4280.88 64-bit, Firefox 83.0 64-bit, Microsoft Edge 87.0.664.66 64-bit

![75a90aa09940d1f240109f88b35b048c](https://user-images.githubusercontent.com/73018717/104843582-bd273200-58cb-11eb-8a69-5d783a2c5db8.gif)

**Comment by revir** [comment]
It's a very tricky problem, I'm going to leave it at the moment.
