### ISSUE TITLE
"Open the lookup history" shortcut works incorrectly

### ISSUE THREAD

**Issue by s23706** [pnlpal/dictionaries#42]
**Steps to reproduce:**
1. Go to hotkeys settings
2. Set up a hotkey for the "Open the lookup history" option
3. Close settings
4. Use the hotkey
5. Verify the result

**Expected result**
Lookup history is opened.

**Actual result**
Lookup history is not opened.

**Environments:** Chrome 87.0.4280.88 64-bit, Firefox 83.0 64-bit, Microsoft Edge 87.0.664.66 64-bit

**Comment by revir** [comment]
I believe it actually works, but not quite accurate.
