### ISSUE TITLE
Rate options are shown when word is not selected

### ISSUE THREAD

**Issue by s23706** [pnlpal/dictionaries#44]
**Steps to reproduce:**
1. Open app pop-up
**Note:** there should be no word selected

**Expected result**
Rate options are not shown.

**Actual result**
Rate options are shown. See the attachment.

**Environments:** Chrome 87.0.4280.88 64-bit, Firefox 83.0 64-bit, Microsoft Edge 87.0.664.66 64-bit

![tempsnip](https://user-images.githubusercontent.com/73018717/104843897-51de5f80-58cd-11eb-921b-c9dc727a26ac.png)

**Comment by revir** [comment]
Damn, you are really good. 
Thank you so much!
