### ISSUE TITLE
能不能不要往富文本編輯框中添加div?

### ISSUE THREAD

**Issue by zzzgit** [pnlpal/dictionaries#45]
![image](https://user-images.githubusercontent.com/1060733/107515277-c31be480-6be5-11eb-924f-07ab80822d87.png)

.

在用富文本編輯框編輯文字之後，我切換到源代碼模式查看HTML代碼，發現這個擴展添加了一些冗餘代碼進去，十分惱人。請問可以改進嗎？

**Comment by revir** [comment]
oh, 似乎这个编辑器在一个iframe里面。能给我个地址吗？我测试一下。

**Comment by zzzgit** [comment]
> oh, 似乎这个编辑器在一个iframe里面。能给我个地址吗？我测试一下。

谷歌的blogger

**Comment by zzzgit** [comment]
如果是editable，就不添加這些代碼，好像還是可以解決的

**Comment by zzzgit** [comment]
下版能解決這個問題嗎？或者用URL白名單的方式？

**Comment by revir** [comment]
嗯，可以的，预计本周内发布下个版本。

Best regards
-----------
*River Yang*


zzzgit ***@***.***> 于2021年3月10日周三 下午6:44写道：

**Comment by revir** [comment]
@zzzgit 
这个问题在新版本 v2.7.4 已解决， Chrome 版本需要等待审核2-3天。Firefox 版本已就绪。
