### ISSUE TITLE
Pop-up definition no longer displays

### ISSUE THREAD

**Issue by travisterrell** [pnlpal/dictionaries#47]
Hi,

I've been using this app for a couple of weeks now, and it's fantastic--by far the best I've used. Unfortunately, I am no longer getting pop-up definitions upon double-clicking/selecting a word. I checked for any settings settings that may be relevant, but had no luck. After this, I tried removing and re-adding the extension. However, it looks like Firefox preserves your add-on settings! I searched around for how to delete these without much luck, other than to learn that it may involve tracking down the correct keys in about:config (in my case, none of the modified key/value pairs jumped out at me as related to this extension.)

What should I try to get this activity back? It's very frustrating, as just after finding the ideal tool, it died! Ha. I imagine that a complete reset the extension data would probably fix it up, but I suppose I would need to know where to find this data. Otherwise, perhaps I'm just misunderstanding some setting (which a reset would've also fixed, heh.)

Thanks in advance for any help you can provide!

**Comment by travisterrell** [comment]
Edit:

**Comment by revir** [comment]
Sorry for your trouble. But which setting caused you misunderstood? I'm also wondering if you have any suggestion of all the settings since they are indeed confusing. 
Thanks for your feedback anyway. I'm glad it's helpful to you :)
