### ISSUE TITLE
Remove "Share with pals".

### ISSUE THREAD

**Issue by chinook77** [pnlpal/dictionaries#48]
Hi, I want to remove the "Share with pals" right menu item. I can't find how to do it in the settings. Thanks in advance.

Best regards.

**Comment by revir** [comment]
Hi, you can disable the context menu with this option:
![image](https://user-images.githubusercontent.com/3252034/117613383-68206c00-b199-11eb-8607-2b69d7bde3ca.png)
But if so, you will not be able to look up words with the context menu either. is it ok for you?

**Comment by chinook77** [comment]
Hi, Thanks for the response. I should have mentioned that I have made this request because I don't want to lose the context menu entry to look up words. Only the share option.

**Comment by revir** [comment]
Add the setting in v2.8.0, take a look.

**Comment by chinook77** [comment]
> 
> 
> Add the setting in v2.8.0, take a look.

Thank you very much.
