### ISSUE TITLE
Clipboard search

### ISSUE THREAD

**Issue by NukaColaQuantum666** [pnlpal/dictionaries#51]
Is it possible to add a hotkey for clipboard search in the dictionary? it's handy when using this extension with other ones, for example, I have an OCR extension that saves the image text in the clipboard and due to chrome security policy, I can't use the dictionary on that extension, if clipboard search exists, it will save a good amount of time and tons of unnecessary clicks, thanks.

**Comment by revir** [comment]
With v2.9.0 reading & watching clipboard is supported on Chrome. But since it's a browser ext, it can only watch clipboard event triggered in the browser.
