### ISSUE TITLE
Leo German-English Translation

### ISSUE THREAD

**Issue by 1dream** [pnlpal/dictionaries#52]
Is there a way to add and test my own dictionaries?

Please add
{
    "dictName": "Leo EN- DE", 
    "windowUrl": "https://dict.leo.org/german-english/<word>?side=left"
}
{
    "dictName": "Leo DE-EN", 
    "windowUrl": "https://dict.leo.org/german-english/<word>?side=right"
}

**Comment by revir** [comment]
Yeah, I added them here: https://pnlpal.dev/tags/german

Sure you can add and test new dicts. Please read this post: https://pnlpal.dev/topic/52/help-more-dictionaries-are-needed
