### ISSUE TITLE
Images can not be added via AnkiWeb - suggestion to use AnkiConnect

### ISSUE THREAD

**Issue by suvkos** [pnlpal/dictionaries#67]
I tried making an anki card with an image how you showed in the [screencast](https://github.com/pnlpal/dictionaries/blob/master/readme_images/optimized.gif) but it didn't work. I got the following message on saving:

ankiuser.net says
"Sorry, images can not be added via AnkiWeb. Please use the computer version or a mobile client."

I suggest making an option for creating cards via the computer version using [AnkiConnect](https://github.com/FooSoft/anki-connect) to enable saving cards with images using the browser extension.

**Comment by revir** [comment]
Finally with v2.9.2 it has been fixed. Thanks.
