### ISSUE TITLE
It conflicts with a 'Free code camp' task

### ISSUE THREAD

**Issue by Polyversetraveler** [pnlpal/dictionaries#70]
This app makes an error in 'freecodecamp'-'Responsive Web Design Certification'-'Applied Visual Design'-'Set the font-size for Multiple Heading Elements' task.

I could't move on finishing the given task correctly, but was able to after turning it off.

I had a similar trouble with 'Dark Reader' app during the course for a changing font-color task. 

So I figured out that this too must had been a problem related to some google extensions. 

This time it was 'dictionaries.'

Anyway, I really love your app and tremendouasly appreciate the convinience I had with it while working. 

Thank you for your work!

**Comment by revir** [comment]
Finally now I got time to fix this. Now you'll see that you can "disable" this ext on specific websites. This is the best way that I can think of.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/3252034/153776465-0f6e9106-800a-47b7-b567-55dca27be351.png">
